name = "mulyono"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "8.219.211.170"
UUID = "b501d66a-9fe8-476b-bdb4-f09cb2699220"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
